name: npm test CI

on:
  pull_request:
  push:
    branches:
      - develop
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set up nodejs and npm
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install npm packages & Run test
      run: |
        npm install
        npm test
      working-directory: ./event-reminder

