name: npm test CI

on:
  pull_request:
  push:
    branches:
      - develop
      - master

steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2
  with:
    node-version: '14'
- run: |
    npm install
    npm test
  working-directory: ./event-reminder

